# General configuration
randomise_seed_number: -1 # if -1 than time is used, > 0 than this number is used
configuration_id: "test"
save_images: false

# GLS configuration
sigma: 0.5
sigma_c: 0
gamma: 0.1
R_field: 100
M_avg: 1.0
dt: 1
t_max: 2

# Rays configuration
R_rays: 100
dx_rays: 0.013

# Image definitions
image_width: 1000
image_height: 1000

image_y1_width: 50.0
image_y2_height: 50.0

image_center_y1: 0.0
image_center_y2: 0.0

## real    0m12.636s
## user    0m7.562s
## sys     0m4.993s
