# General configuration
randomise_seed_number: 0 # if -1 than time is used, > 0 than this number is used
configuration_id: "test"
save_images: true
output_rays: false

# GLS configuration
sigma: 0.5
sigma_c: 0
gamma: 0.1
R_field: 100 # the radius of microlenses field
M_max: 1.0 # the microlenses masses will be in the range [0, M_max]
V_max: 1.0 # the microlenses velocities will be in the range [-V_max, V_max]
dt: 0.1 # time step
t_max: 25 # time will be in the range [0, t_max] with the step dt

# Rays configuration
R_rays: 100
dx_rays: 0.03

# Output image definitions
image_width: 1000
image_height: 1000

image_y1_left: -15
image_y2_bottom: -15
image_y1_right: 15
image_y2_top: 15

# LC configuration
lc_enabled: true
lc_start_y1: -10
lc_start_y2: -1
lc_end_y1: 10
lc_end_y2: 1
lc_step: 0.01

# Sources configuration
source_size: 0.2

##########################
# GPU:  MSI P104-100 8GB #
##########################

## output_rays: false
# Raytracing time: 16.3184s (mean: 1.63184s)
# Output time: 12.3643s (mean: 1.23643s)
# real    0m29.904s
# user    0m14.990s
# sys     0m14.754s
