# GLS configuration
sigma: 0.5
sigma_c: 0
gamma: 0.1
R_field: 100
M_avg: 1.0
dt: 0.1
t_max: 0.1

# Rays configuration
R_rays: 100
dx_rays: 0.1

# Image definitions
image_width: 500
image_height: 500

image_y_width: 30.0
image_y_height: 30.0

image_center_y1: 0.0
image_center_y2: 0.0

# General configuration
randomise_with_time: false
