# General configuration
randomise_seed_number: 12222234 # if -1 than time is used, > 0 than this number is used
configuration_id: "e0.1"
save_images: true
output_rays: false
debug: false
operation_mode: 0 # 0 - evolve microlenses positions using V_max on each step, 1 - randomize microlenses positions on each step. The dt and t_max are used to define number of steps.

# GLS configuration
sigma: 0.5
sigma_c: 0
gamma: 0.1
R_field: 100 # the radius of microlenses field
M_max: 1.0 # the microlenses masses will be in the range (0, M_max)
V_max: 1.0 # the microlenses velocities will be in the range (-V_max, V_max)
dt: 0.1 # time step
t_max: 50 # time will be in the range [0, t_max) with a step dt

# Rays configuration
R_rays: 100
dx_rays: 0.03

# Output image definitions
image_width: 1000
image_height: 1000

image_y1_left: -15
image_y2_bottom: -15
image_y1_right: 15
image_y2_top: 15

# LC configuration
lc_enabled: true
lc_start_y1: -10
lc_start_y2: -5
lc_angle: 1 # degrees
lc_dist_max: 20
lc_dist_step: 0.05

# Sources configuration
source_size: 0.2
eccentricity: 0.1
p_ld: 2.0
p_pl: 1.5

##########################
# GPU:  MSI P104-100 8GB #
##########################
# Raytracing time: 831.744s (mean: 1.66017s)
# Output time: 10.7794s (mean: 0.0215158s)
# Total time: 881.059s
#
# real    14m41.188s
# user    10m24.073s
# sys     4m14.359s
