# GLS configuration
sigma: 0.9
sigma_c: 0
gamma: 0.1
R_field: 10
M_avg: 1.0
dt: 0.1
t_max: 0.1

# Rays configuration
R_rays: 100
dx_rays: 0.0135

# Image definitions
image_width: 500
image_height: 500

image_y1_width: 40.0
image_y2_height: 40.0

image_center_y1: 0.0
image_center_y2: 0.0

# General configuration
randomise_with_time: false
