# General configuration
randomise_with_time: false
configuration_id: "test"

# GLS configuration
sigma: 0.5
sigma_c: 0
gamma: 0.1
R_field: 100
M_avg: 1.0
dt: 0.1
t_max: 100

# Rays configuration
R_rays: 100
dx_rays: 0.05

# Image definitions
image_width: 500
image_height: 500

image_y1_width: 30.0
image_y2_height: 30.0

image_center_y1: 0.0
image_center_y2: 0.0

## real    0m12.636s
## user    0m7.562s
## sys     0m4.993s
